-- MySQL Script generated by MySQL Workbench
-- ter 11 set 2018 12:14:38 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema speech_api
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema speech_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `speech_api` ;
USE `speech_api` ;

-- -----------------------------------------------------
-- Table `speech_api`.`paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speech_api`.`paciente` ;

CREATE TABLE IF NOT EXISTS `speech_api`.`paciente` (
  `id_paciente` INT NOT NULL AUTO_INCREMENT,
  `aquisicao` CHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `data_cadastro` DATE NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `escola` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `nome` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `escola_tipo` CHAR(3) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `responsavel` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `sexo` CHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `telefone` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `cidade` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `endereco` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `uf` CHAR(2) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`id_paciente`),
  UNIQUE INDEX `id_paciente_UNIQUE` (`id_paciente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speech_api`.`avaliacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speech_api`.`avaliacao` ;

CREATE TABLE IF NOT EXISTS `speech_api`.`avaliacao` (
  `id_avaliacao` INT NOT NULL AUTO_INCREMENT,
  `data_av` DATE NOT NULL,
  `tipo` CHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_avaliacao`),
  UNIQUE INDEX `id_avaliacao_UNIQUE` (`id_avaliacao` ASC) VISIBLE,
  INDEX `fk_avaliacao_paciente_idx` (`id_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_paciente`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `speech_api`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speech_api`.`palavra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speech_api`.`palavra` ;

CREATE TABLE IF NOT EXISTS `speech_api`.`palavra` (
  `id_palavra` INT NOT NULL AUTO_INCREMENT,
  `dica` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `img_link` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `ordem` INT NOT NULL,
  `palavra` VARCHAR(255) NOT NULL,
  `som_link` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`id_palavra`),
  UNIQUE INDEX `id_palavra_UNIQUE` (`id_palavra` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speech_api`.`historia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speech_api`.`historia` ;

CREATE TABLE IF NOT EXISTS `speech_api`.`historia` (
  `id_historia` INT NOT NULL AUTO_INCREMENT,
  `img1_link` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `img2_link` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `img3_link` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `img4_link` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `ordem` INT NOT NULL,
  PRIMARY KEY (`id_historia`),
  UNIQUE INDEX `id_historia_UNIQUE` (`id_historia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speech_api`.`fonema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speech_api`.`fonema` ;

CREATE TABLE IF NOT EXISTS `speech_api`.`fonema` (
  `id_fonema` INT NOT NULL AUTO_INCREMENT,
  `articulacao` CHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `estrutura` CHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `fonema` CHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`id_fonema`),
  UNIQUE INDEX `id_fonema_UNIQUE` (`id_fonema` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speech_api`.`transcricao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speech_api`.`transcricao` ;

CREATE TABLE IF NOT EXISTS `speech_api`.`transcricao` (
  `id_transcricao` INT NOT NULL AUTO_INCREMENT,
  `transcricao` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `tipo` INT NOT NULL,
  `id_palavra` INT NOT NULL,
  PRIMARY KEY (`id_transcricao`),
  UNIQUE INDEX `id_transcricao_UNIQUE` (`id_transcricao` ASC) VISIBLE,
  INDEX `fk_transcricao_palavra1_idx` (`id_palavra` ASC) VISIBLE,
  CONSTRAINT `fk_transcricao_palavra1`
    FOREIGN KEY (`id_palavra`)
    REFERENCES `speech_api`.`palavra` (`id_palavra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speech_api`.`avaliacao_palavra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speech_api`.`avaliacao_palavra` ;

CREATE TABLE IF NOT EXISTS `speech_api`.`avaliacao_palavra` (
  `id_avaliacao_palavra` INT NOT NULL AUTO_INCREMENT,
  `id_alvo` INT NOT NULL,
  `audio_link` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `repeticao` INT NOT NULL,
  `transcricao` VARCHAR(255) NOT NULL,
  `id_avaliacao` INT NOT NULL,
  `id_palavra` INT NOT NULL,
  PRIMARY KEY (`id_avaliacao_palavra`),
  UNIQUE INDEX `id_avaliacao_palavra_UNIQUE` (`id_avaliacao_palavra` ASC) VISIBLE,
  INDEX `fk_avaliacao_palavra_transcricao1_idx` (`id_alvo` ASC) VISIBLE,
  INDEX `fk_avaliacao_palavra_avaliacao1_idx` (`id_avaliacao` ASC) VISIBLE,
  INDEX `fk_avaliacao_palavra_palavra1_idx` (`id_palavra` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_palavra_transcricao1`
    FOREIGN KEY (`id_alvo`)
    REFERENCES `speech_api`.`transcricao` (`id_transcricao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_palavra_avaliacao1`
    FOREIGN KEY (`id_avaliacao`)
    REFERENCES `speech_api`.`avaliacao` (`id_avaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_palavra_palavra1`
    FOREIGN KEY (`id_palavra`)
    REFERENCES `speech_api`.`palavra` (`id_palavra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speech_api`.`avaliacao_historia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speech_api`.`avaliacao_historia` ;

CREATE TABLE IF NOT EXISTS `speech_api`.`avaliacao_historia` (
  `id_avaliacao_historia` INT NOT NULL AUTO_INCREMENT,
  `audio_link` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `transcricao` VARCHAR(2000) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `id_avaliacao` INT NOT NULL,
  `id_historia` INT NOT NULL,
  PRIMARY KEY (`id_avaliacao_historia`),
  UNIQUE INDEX `id_avaliacao_historia_UNIQUE` (`id_avaliacao_historia` ASC) VISIBLE,
  INDEX `fk_avaliacao_historia_avaliacao1_idx` (`id_avaliacao` ASC) VISIBLE,
  INDEX `fk_avaliacao_historia_historia1_idx` (`id_historia` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_historia_avaliacao1`
    FOREIGN KEY (`id_avaliacao`)
    REFERENCES `speech_api`.`avaliacao` (`id_avaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_historia_historia1`
    FOREIGN KEY (`id_historia`)
    REFERENCES `speech_api`.`historia` (`id_historia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speech_api`.`avaliacao_palavra_fonema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speech_api`.`avaliacao_palavra_fonema` ;

CREATE TABLE IF NOT EXISTS `speech_api`.`avaliacao_palavra_fonema` (
  `id_av_palavra_fonema` INT NOT NULL AUTO_INCREMENT,
  `posicao` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `tipo` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `troca` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `id_avaliacao_palavra` INT NOT NULL,
  `id_fonema` INT NOT NULL,
  PRIMARY KEY (`id_av_palavra_fonema`),
  UNIQUE INDEX `id_av_palavra_fonema_UNIQUE` (`id_av_palavra_fonema` ASC) VISIBLE,
  INDEX `fk_avaliacao_palavra_fonema_avaliacao_palavra1_idx` (`id_avaliacao_palavra` ASC) VISIBLE,
  INDEX `fk_avaliacao_palavra_fonema_fonema1_idx` (`id_fonema` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_palavra_fonema_avaliacao_palavra1`
    FOREIGN KEY (`id_avaliacao_palavra`)
    REFERENCES `speech_api`.`avaliacao_palavra` (`id_avaliacao_palavra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_palavra_fonema_fonema1`
    FOREIGN KEY (`id_fonema`)
    REFERENCES `speech_api`.`fonema` (`id_fonema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speech_api`.`anamnese`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speech_api`.`anamnese` ;

CREATE TABLE IF NOT EXISTS `speech_api`.`anamnese` (
  `id_anamnese` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_anamnese`),
  UNIQUE INDEX `id_anamnese_UNIQUE` (`id_anamnese` ASC) VISIBLE,
  INDEX `fk_anamnese_paciente1_idx` (`id_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_anamnese_paciente1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `speech_api`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speech_api`.`avaliacao_anamnese`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speech_api`.`avaliacao_anamnese` ;

CREATE TABLE IF NOT EXISTS `speech_api`.`avaliacao_anamnese` (
  `id_avaliacao_anamnese` INT NOT NULL AUTO_INCREMENT,
  `campo` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `dado` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `id_anamnese` INT NOT NULL,
  PRIMARY KEY (`id_avaliacao_anamnese`),
  UNIQUE INDEX `id_avaliacao_anamnese_UNIQUE` (`id_avaliacao_anamnese` ASC) VISIBLE,
  INDEX `fk_avaliacao_anamnese_anamnese1_idx` (`id_anamnese` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_anamnese_anamnese1`
    FOREIGN KEY (`id_anamnese`)
    REFERENCES `speech_api`.`anamnese` (`id_anamnese`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speech_api`.`timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speech_api`.`timestamps` ;

CREATE TABLE IF NOT EXISTS `speech_api`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
