INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (1, 'Cavalo', 'Que bicho é este?', 0);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (2, 'Gritar', 'O menino vai ...?', 1);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (3, 'Sapo', 'Que bicho é este?', 2);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (4, 'Bruxa', 'Ela está fazendo feitiço. Ela é uma ...?', 3);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (5, 'Jacaré', 'Que bicho é este?', 4);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (6, 'Chiclete', 'O menino está matigando o ...?', 5);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (7, 'Cama', 'O que é isto?', 6);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (8, 'Livro', 'O que é isto?', 7);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (9, 'Sofá', 'O que é isto?', 8);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (10, 'Nuvem', 'O que é isto?', 9);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (11, 'Prato', 'O que é isto?', 10);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (12, 'Relógio', 'O que é isto?', 11);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (13, 'Cabelo', 'O que é isto?', 12);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (14, 'Letra', 'Não são números são?', 13);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (15, 'Cruz', 'O que é isto?', 14);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (16, 'Beijo', 'O menino vai dar um ...?', 15);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (17, 'Girafa', 'Que bicho é este?', 16);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (18, 'Língua', 'O que é isto?', 17);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (19, 'Folha', 'O que é isto?', 18);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (20, 'Flor', 'O que é isto?', 19);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (21, 'Coelho', 'Que bicho é este?', 20);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (22, 'Escrever', 'Ele está usando o lápis para ...?', 21);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (23, 'Placa', 'O que é isto?', 22);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (24, 'Estrela', 'O que é isto?', 23);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (25, 'Sapato', 'O que é isto?', 24);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (26, 'Casa', 'O que é isto?', 25);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (27, 'Fruta', 'Maçã, pêra, laranja são ...?', 26);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (28, 'Lápis', 'O que é isto?', 27);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (29, 'Faca', 'O que é isto?', 28);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (30, 'Presente', 'O que é isto?', 29);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (31, 'Dedo', 'A mão tem ...?', 30);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (32, 'Plástico', 'Este copo não é de vidro é de ...?', 31);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (33, 'Espelho', 'O menino está olhando no ...?', 32);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (34, 'Refri', 'É uma garrafa de ...?', 33);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (35, 'Cachorro', 'Que bicho é este?', 34);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (36, 'Magro', 'Um é gordo e o outro é ...?', 35);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (37, 'Microfone', 'O que é isto?', 36);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (38, 'Nariz', 'Que parte do corpo é esta?', 37);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (39, 'Barriga', 'Que parte do corpo é esta?', 38);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (40, 'Grama', 'O que é isto?', 39);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (41, 'Caminhão', 'O que é isto?', 40);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (42, 'Tênis', 'O que é isto?', 41);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (43, 'Mesa', 'O que é isto?', 42);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (44, 'Anel', 'O que é isto?', 43);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (45, 'Garfo', 'O que é isto?', 44);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (46, 'Vidro', 'Nesta janela tem ...?', 45);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (47, 'Igreja', 'Que lugar é este?', 46);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (48, 'Trem', 'O que é isto?', 47);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (49, 'Caixa', 'O que é isto?', 48);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (50, 'Tesoura', 'O que é isto?', 49);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (51, 'Pedra', 'O que é isto?', 50);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (52, 'Jornal', 'O que é isto?', 51);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (53, 'Fralda', 'O bebê usa ...?', 52);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (54, 'Travesseiro', 'O que é isto?', 53);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (55, 'Chinelo', 'O que é isto?', 54);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (56, 'Bolsa', 'O que é isto?', 55);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (57, 'Soprar', 'Para apagar a vela, o menino vai ...?', 56);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (58, 'Fogo', 'O que é isto?', 57);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (59, 'Zebra', 'Que bicho é este?', 58);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (60, 'Vaca', 'Que bicho é este?', 59);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (61, 'Colher', 'O que é isto?', 60);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (62, 'Chapéu', 'O que é isto?', 61);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (63, 'Gato', 'Que bicho é este?', 62);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (64, 'Floresta', 'Um monte de árvores formam uma ...?', 63);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (65, 'Bebê', 'Ele é um ...?', 64);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (66, 'Pastel', 'O que é isto?', 65);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (67, 'Porta', 'O que é isto?', 66);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (68, 'Zero', 'Que número é este?', 67);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (69, 'Brinco', 'O que é isto?', 68);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (70, 'Dado', 'O que é isto?', 69);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (71, 'Dente', 'O que é isto?', 70);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (72, 'Galinha', 'Que bicho é este?', 71);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (73, 'Batom', 'O que é isto?', 72);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (74, 'Bicicleta', 'O que é isto?', 73);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (75, 'Rabo', 'O cachorro tem um ...?', 74);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (76, 'Terra', 'Ele está plantando na ...?', 75);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (77, 'Chifre', 'O touro tem ...?', 76);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (78, 'Navio', 'É de pirata, é um ...?', 77);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (79, 'Dragão', 'Que bicho é este?', 78);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (80, 'Biblioteca', 'Que lugar é este?', 79);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (81, 'Calça', 'O que é isto?', 80);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (82, 'Ventilador', 'O que é isto?', 81);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (83, 'Passarinho', 'Que bicho é este?', 82);
INSERT INTO speech_api.words (id, word, tip, `order`) VALUES (84, 'Cobra', 'Que bicho é este?', 83);