"""add user token

Revision ID: 280f32924af0
Revises: 6bd7e8aa157d
Create Date: 2018-10-12 21:08:20.311950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '280f32924af0'
down_revision = '6bd7e8aa157d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revoked_tokens', sa.Column('token', sa.String(length=120), nullable=True))
    op.drop_column('revoked_tokens', 'jti')
    op.add_column('users', sa.Column('token', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.drop_column('users', 'token')
    op.add_column('revoked_tokens', sa.Column('jti', mysql.VARCHAR(collation='utf8_bin', length=120), nullable=True))
    op.drop_column('revoked_tokens', 'token')
    # ### end Alembic commands ###
