"""remove dictalchemy

Revision ID: 6bd7e8aa157d
Revises: c5fe5bc8c79c
Create Date: 2018-10-08 23:52:38.510471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd7e8aa157d'
down_revision = 'c5fe5bc8c79c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_evaluation',
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('transcription_target_id', sa.Integer(), nullable=True),
    sa.Column('transcription_eval', sa.String(length=255), nullable=True),
    sa.Column('repetition', sa.Boolean(), nullable=True),
    sa.Column('audio_path', sa.String(length=255), nullable=False),
    sa.Column('ml_eval', sa.Boolean(), nullable=True),
    sa.Column('api_eval', sa.Boolean(), nullable=True),
    sa.Column('therapist_eval', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['transcription_target_id'], ['transcription.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('evaluation_id', 'word_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_evaluation')
    # ### end Alembic commands ###
