"""empty message

Revision ID: a4aae55d3c89
Revises: 65b5b5b0de78
Create Date: 2018-11-10 00:47:54.011976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4aae55d3c89'
down_revision = '65b5b5b0de78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'complete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('word_evaluation', sa.Column('transcription_eval_id', sa.Integer(), nullable=True))
    op.alter_column('word_evaluation', 'api_eval',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('word_evaluation', 'ml_eval',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('word_evaluation', 'repetition',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('word_evaluation', 'therapist_eval',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.create_foreign_key(None, 'word_evaluation', 'transcription', ['transcription_eval_id'], ['id'])
    op.drop_column('word_evaluation', 'transcription_eval')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_evaluation', sa.Column('transcription_eval', mysql.VARCHAR(collation='utf8_bin', length=255), nullable=True))
    op.drop_constraint(None, 'word_evaluation', type_='foreignkey')
    op.alter_column('word_evaluation', 'therapist_eval',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('word_evaluation', 'repetition',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('word_evaluation', 'ml_eval',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('word_evaluation', 'api_eval',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('word_evaluation', 'transcription_eval_id')
    op.alter_column('tasks', 'complete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
